org.gradle.jvmargs=-Xmx1G

# Project settings
project_version=26.9-tgcs3
project_group=net.momirealms

# Dependency settings
velocity_version=4.1.1-SNAPSHOT
bungeecord_version=1.21-R0.4-SNAPSHOT
waterfall_version=1.21
jetbrains_annotations_version=26.1.0
gson_version=2.13.2
adventure_bundle_version=5.1.1
bstats_version=3.2.1
caffeine_version=3.2.3
sparrow_nbt_version=0.18.4
sparrow_reflection_version=0.32
netty_version=4.1.132.Final
